iotsound/iotsound

- bluetooth-audio/Dockerfile.template
> Remove redundant alsa-base package

- bluetooth-audio/Dockerfile.template
> Remove redundant bluealsa package

- bluetooth-audio/Dockerfile.aarch64
> Add support for Pi 4 fixes #25

- README.md
- bluetooth-audio/bluetooth-udev
- bluetooth-audio/start.sh
> Add volume configuration options, fixes #28

- docker-compose.yml
- spotify/Dockerfile.template
- spotify/start.sh
> Add Spotify Support

- .github/CODEOWNERS
> Update CODEOWNERS (add @shaunmulligan)

- .github/CODEOWNERS
Signed-off-by: Matthew McGinn <matthew@balena.io>
> meta: add tmigone as a codeowner

- README.md
> Add other supported streaming methods to README

- README.md
- airplay/start.sh
- bluetooth-audio/Dockerfile.aarch64
- bluetooth-audio/Dockerfile.template
- bluetooth-audio/bluetooth-scripts/bluetooth-connect
- bluetooth-audio/bluetooth-scripts/bluetooth-disconnect
- bluetooth-audio/bluetooth-udev
Connects-to: #22
Hi @tmigone . I wrote with @johnborgesfl in his issue. He asked for code like this and i have now this. 
I think everyone needs his own specific code so should my python script be usefull.
suggestions:
> Add code for gpio control with udev and some other things

- README.md
> Clarify Spotify connect usage

- README.md
Signed-off-by: Heds Simons <heds@balena.io>
Have you taken a look at the [contribution guidelines](../CONTRIBUTING.md) for this project? To enable our CI to work correctly and version the releases of the project, you need to ensure your commit messages contain the required information [detailed here](../CONTRIBUTING.md). Thank you!
> readme: Clarify Spotify only works with Premium account

- DAC_configuration.md
- airplay/start.sh
- bluetooth-audio/bluetooth-udev
- bluetooth-audio/start.sh
- spotify/start.sh
Tested and added docs for DACs: Justboom DAC HAT and Blokas Pisound.
Also reduced default system volume.
> Add DAC docs

- README.md
User mentioned it here: https://forums.balena.io/t/regarding-dac-installation-on-balenasound-project/45568
Signed-off-by: Stevche Radevski <stevche@balena.io>
Have you taken a look at the [contribution guidelines](../CONTRIBUTING.md) for this project? To enable our CI to work correctly and version the releases of the project, you need to ensure your commit messages contain the required information [detailed here](../CONTRIBUTING.md). Thank you!
> Fix default volume value in README

- README.md
> upd information re. pHAT DAC

- DAC_configuration.md
@Fiqq90 does it work with this dtoverly value?
> Add Pimoroni Pirate Audio to list

- docker-compose.yml
- snapcast-client/Dockerfile.aarch64
- snapcast-client/Dockerfile.template
- snapcast-server/Dockerfile.aarch64
- snapcast-server/Dockerfile.template
> Bump Snapcast to 0.19.0

- bluetooth-audio/Dockerfile.aarch64
> Delete mplayer in aarch64

- .github/CODEOWNERS
> Add AlexProgrammerDE as codeowner

- README.md
> Add acks for projects we're using

- bluetooth-audio/bluetooth-udev
- bluetooth-audio/start.sh
Details of this are in the following issue comment. 
https://github.com/balenalabs/balena-sound/issues/117#issuecomment-609097464
> add -M to amixer to fix volume mapping issues #117

- repo.yml
> Change to balena project to enable builds in CI

- DAC_configuration.md
> Add more DACs

- DAC_configuration.md
> Added Justboom Digi HAT dtoverlay config info.

- README.md
This is ready to be merged now as is. I'd like to add a config file as well with all the default environment variables, but I have some questions there so we can leave it for a follow-up PR.
Signed-off-by: Stevche Radevski <stevche@balena.io>
> Add sample "deploy to balena" button

- .versionbot/CHANGELOG.yml
Signed-off-by: Giovanni Garufi <giovanni@balena.io>
Have you taken a look at the [contribution guidelines](../CONTRIBUTING.md) for this project? To enable our CI to work correctly and version the releases of the project, you need to ensure your commit messages contain the required information [detailed here](../CONTRIBUTING.md). Thank you!
> Add parsable CHANGELOG

- README.md
Via @sradevski 
Have you taken a look at the [contribution guidelines](../docs/CONTRIBUTING.md) for this project? To enable our CI to work correctly and version the releases of the project, you need to ensure your commit messages contain the required information [detailed here](../docs/CONTRIBUTING.md). Thank you!
> Put back one-click deploy button on main README file.

- .github/ISSUE_TEMPLATE/config.yml
People should follow our templates.
> Add config.yml

- docs/01-getting-started.md
Signed-off-by: Phil Wilson <phil@balena.io>
Have you taken a look at the [contribution guidelines](../docs/CONTRIBUTING.md) for this project? To enable our CI to work correctly and version the releases of the project, you need to ensure your commit messages contain the required information [detailed here](../docs/CONTRIBUTING.md). Thank you!
> Minor documentation updates

- .github/PULL_REQUEST_TEMPLATE.md
Have you taken a look at the [contribution guidelines](../docs/CONTRIBUTING.md) for this project? To enable our CI to work correctly and version the releases of the project, you need to ensure your commit messages contain the required information [detailed here](../docs/CONTRIBUTING.md). Thank you!
> Contribution link patch

- docs/06-troubleshooting.md
> docs: add delay reduction troubleshooting for bluetooth-audio

- snapcast-client/start.sh
> snapcast-client: Fix bug where snapcast client is not starting

- docs/05-device-support.md
> docs: Update device support citations so they don't look as links

- docs/06-troubleshooting.md
No audio on Pi3 with balenaOS 64bits.
> docs: add troubleshooting case

- docs/06-troubleshooting.md
Added section to docs/troubleshooting to reference and recommend taking masterclasses.
Signed-off-by: Andrew Nhem <andrewn@balena.io>
> Adding masterclass reference to balenaSound troubleshooting

- airplay/start.sh
- bluetooth-audio/start.sh
- fleet-supervisor/server.js
- snapcast-server/start.sh
- spotify/start.sh
- upnp/start.sh
> multi-room: disable feature for raspberrypi2 fam

- airplay/start.sh
- fleet-supervisor/server.js
- spotify/start.sh
- upnp/start.sh
> Fix rpi1/rpi2 bug with multiroom server

- docker-compose.yml
- snapcast-client/Dockerfile.template
- snapcast-server/Dockerfile.template
> Fix snapcast bad signature error in rpi0 devices

- ARCHITECTURE.md
> docs: Fix some formatting in ARCHITECTURE.md

- README.md
Signed-off-by: Amit Solanki <amit@balena.io>
> Update logo dir in README

- docs/05-audio-interfaces.md
> dac: add Hifiberry DAC2 HD

- README.md
- docs/01-getting-started.md
- docs/02-usage.md
- docs/03-customization.md
- docs/04-device-support.md
- docs/05-audio-interfaces.md
- docs/06-support.md
I may fix some other stuff. Still draft.
> Minor documentation tweaks

- docker-compose.yml
> plugins: change restart policy to on-failure to avoid unnecessary restarts

- docs/05-audio-interfaces.md
> dac: add Adafruit mac98357

- README.md
Signed-off-by: Aaron Shaw <shawaj@gmail.com>
> docs: add query params to deploy link

- docs/05-audio-interfaces.md
Setting to `draft` as we work out the landr bug that breaks the website on PR merge. Might take a few days as we are on annual team summit.
Connects-to: #305
Signed-off-by: Tomás Migone <tomasmigone@gmail.com>
> dac: Add Boss DAC v1.2

- balena.yml
> dwb: add balena.yml file to explicitly set env vars

- plugins/spotify/start.sh
> spotify: fix password woes

- docs/01-getting-started.md
- docs/03-customization.md
- docs/05-audio-interfaces.md
- docs/06-support.md
Signed-off-by: Matthew McGinn <matthew@balena.io>
> meta: fix up some docs typos

- docs/05-audio-interfaces.md
> Replace Unicode double quotes with ASCII double quotes in reference docs

- ARCHITECTURE.md
> docs: Patch ALSA bridge install script

- docs/05-audio-interfaces.md
Add more tested JustBoom and iqaudio boards
Signed-off-by: Aaron Shaw <shawaj@gmail.com>
> docs: add iqaudio and JustBoom boards

- README.md
- docs/01-getting-started.md
- docs/05-audio-interfaces.md
adds instructions for various dacs that have been tested to work with balenaSound
Closes: #385 
Closes: #355 
Closes: #345 
Signed-off-by: Aaron Shaw <aaron@balena.io>
> docs: add various dacs that have been tested

- plugins/upnp/start.sh
[https://github.com/balenalabs/balena-sound/issues/380](https://github.com/balenalabs/balena-sound/issues/380)
> Set the UUID to differentiate between instances

- balena.yml
Signed-off-by: Stevche Radevski <stevche@balena.io>
> Update balena.yml to adhere to new spec

- balena.yml
- core/audio/start.sh
- docker-compose.yml
This PR introduces changes needed for openFleets.
> hub: add open fleets metadata

- .github/ISSUE_TEMPLATE/dac_request.md
- docs/03-customization.md
- docs/05-audio-interfaces.md
> docs: expand DAC docs

- docker-compose.yml
> Remove unneeded ports from sound supervisor service

- core/sound-supervisor/Dockerfile.template
- core/sound-supervisor/src/SoundAPI.ts
- docker-compose.yml
> Expose project version on sound API

- core/multiroom/client/Dockerfile.template
> multiroom: unpin client image

- core/sound-supervisor/src/index.ts
> hub: temporarily track usage

- core/multiroom/client/start.sh
Pulse backend is not working reliably, use alsa instead.
> multiroom: use alsa backend on client

- balena.yml
Signed-off-by: Amit Solanki <amit@balena.io>
> Format Post-provisioning markdown

- docs/02-usage.md
- docs/03-customization.md
> docs: clarify spotify premium requirement

- core/sound-supervisor/Dockerfile.template
- core/sound-supervisor/package-lock.json
- core/sound-supervisor/package.json
Signed-off-by: Flynn Joffray <flynn@balena.io>
Connects-to: #522
> Upgrade sound-supervisor to node 14

- docs/04-plugins.md
> docs: clarify spotify over the internet

- .github/workflows/balena-ci.yml
> ci: use new deploy to balena action

- README.md
> readme: add event link and emojis

- netlify.toml
Signed-off-by: Carlo Miguel F. Cruz <carloc@balena.io>
> Add redirect for balena-sound website.

- README.md
> update meet-up event page URL

- core/audio/Dockerfile.template
- core/hostname/Dockerfile.template
- core/multiroom/client/Dockerfile.template
- core/multiroom/server/Dockerfile.template
- docker-compose.yml
- plugins/bluetooth/Dockerfile.template
> Use balenaHub proxy registry for blocks

- README.md
> Removing meetup banner now that event has ended.

- ARCHITECTURE.md
- CONTRIBUTING.md
- FAQ.md
- README.md
- balena.yml
- core/multiroom/client/start.sh
- core/sound-supervisor/src/ui/index.html
- docs/01-getting-started.md
- docs/04-plugins.md
- docs/05-audio-interfaces.md
- docs/07-support.md
Signed-off-by: Flynn Joffray <flynn@balena.io>
> Changing references from balenalabs to balena-labs-projects

- ARCHITECTURE.md
- README.md
- balena.yml
- docs/01-getting-started.md
- docs/02-usage.md
- docs/04-plugins.md
> Update docs with Airplay2 feature

- .github/workflows/deploy-to-balena.yml
> Allow manual deploys to balena via GH Workflow

- core/audio/balena-sound.pa
- core/multiroom/client/start.sh
- core/sound-supervisor/src/ui/index.html
> Replace 'iotsound/balena-sound' with 'iotsound/iotsound' GitHub references
