iotsound/iotsound

README.md
It's a bit nicer. Name is in the logo and the header fits one line now.
Signed-off-by: Robert Vojta <robert@balena.io>
=> Remove name from the header

README.md, bluetooth-audio/bluetooth-agent, bluetooth-audio/start.sh
* Add space just before the screenshot
* Remove paragraph about service restart (supervisor auto magic)
* Unnecessary output from the logs silenced
```
05.07.19 15:34:22 (+0200)  bluetooth-audio  Setting volume to 100%
05.07.19 15:34:22 (+0200)  bluetooth-audio  Restarting bluetooth service
05.07.19 15:34:26 (+0200)  bluetooth-audio  Bluetooth agent registered
05.07.19 15:34:30 (+0200)  bluetooth-audio  Device is discoverable as "FooBar with Space"
05.07.19 15:39:42 (+0200) Killing service 'bluetooth-audio sha256:cf0190e7a26824470cd0d58287fe015703c9feb6f4f5653fc31c2aee20bc86c1'
05.07.19 15:39:54 (+0200) Service exited 'bluetooth-audio sha256:cf0190e7a26824470cd0d58287fe015703c9feb6f4f5653fc31c2aee20bc86c1'
05.07.19 15:39:54 (+0200) Killed service 'bluetooth-audio …
```
=> Nicer log output

README.md
Maybe some additional info useful for some of the more beginner folks.
=> Suggestion extra instructions

bluetooth-audio/start.sh
Using dbus-send in this manner without --print-reply causes it to
silently fail.
=> Restore disabling timeout functionality

bluetooth-audio/Dockerfile.template
Fixes https://github.com/balena-io-projects/balena-sound/issues/15
The use of Buster instead of Stretch breaks balena-sound. This reverts back to Stretch until the Buster issues can be worked out.
=> Change base image to Debian Stretch instead of Buster

spotify/Dockerfile.aarch64
I had tested this container previously on a Pi4 but it was part of a multi-arch app. This fixes the container for a Pi4 specific app.
=> Fix to make spotify container build for a Pi 4 app

docker-compose.yml, spotify/Dockerfile.aarch64, spotify/Dockerfile.template, spotify/start.sh
I now added some features to spotify connect and improved the music quality.
I have no premium so i could not test it. Thanks in advance.
bugs:
=> Make raspotify more clear, add cache and add default output volume

README.md, airplay/Dockerfile.template, airplay/start.sh, bluetooth-audio/Dockerfile.aarch64, bluetooth-audio/Dockerfile.template, bluetooth-audio/start.sh, docker-compose.yml, spotify/Dockerfile.aarch64, spotify/Dockerfile.template, spotify/start.sh
Various patch changes:
+ bluetooth-audio: removed unnecessary 'io.balena.features.supervisor-api' label (not needed since this [commit](https://github.com/balena-io-projects/balena-sound/commit/51b6254a7893c889947cf2926dc863d1ee75cf95))
+ Readme: Removed mc instructions no longer needed.
+ Updated Dockerfiles to use the exec form of CMD (as per internal discussion)
=> Patch readme exec

README.md, spotify/Dockerfile.aarch64, spotify/Dockerfile.template, spotify/start.sh
Connects-to: #73
Hi,
in this PR i implement the in #73 requested feature.
bugs: 
recommends:
=> Add Spotify login and suppress the build error message

DAC_configuration.md
I've tested an InnoMaker DAC purchased [here](https://www.amazon.com/Inno-Maker-Raspberry-PCM5122-Audio-Expansion/dp/B07D13QWV9/ref=sr_1_4?keywords=rpi+dac&qid=1580918982&sr=8-4) with this configuration and it does work.
Change-Type: patch
=> Add InnoMaker DAC to DAC configuration docs

DAC_configuration.md
https://allo.com/sparky/miniboss-rpi-zero.html
Just got it, works great.
=> dac: Add dtoverlay for miniBoss DAC

DAC_configuration.md
Change-Type: patch
Works fine using the optical cable with the Hifiberry Digi clone PiFi Digi+ using the hifiberry-digi overlay.
This makes it possible to build projects with digital outputs for receivers that do not yet have HDMI.
=> Added PiFi Digi+ to DAC_configuration.md

README.md
Users are often confused when steps happen on the device and which steps should be run from their personal computer. This edit should make that distinction more clear.
Signed-off-by: Stef Kors <stef@balena.io>
=> Readme should show where setup commands are run

docs/03-customization.md
Clarifying and citing resources for env var usage in balenaSound so users don't try to add env vars to config vars.
Signed-off-by: Andrew Nhem <andrewn@balena.io>
=> Adding clarification between config vars and env vars for users

docs/04-dacs.md
Specifying that DAC instructions need to be device-specific to device using DAC and not fleet wide.
Signed-off-by: Andrew Nhem <andrewn@balena.io>
=> Adding clarity to DAC section

spotify/start.sh
spotify: Add volume normalisation switch
this pr adds a new environment variable which will enable and disable volume normalisation
Connects-to:  #267
=> spotify: Environment variable to switch volume normalisation

core/audio/start.sh
Launch pulseaudio with better options
- Use --system=true since we are anyway running it as root.
- Use `--log-target=stderr` and `--daemonize=false` so errors and warnings will
show up better in the logs.
- Use `--realtime=true` to get better performance; Most notably, latency errors are gone thanks to this.
P.S I hope this won't get automatically merged by your bot.
=> balenaSound 3.x - initial version

ARCHITECTURE.md, core/audio/Dockerfile.template, core/multiroom/client/Dockerfile.template, docs/02-usage.md, plugins/bluetooth/Dockerfile.template, plugins/spotify/Dockerfile.aarch64, plugins/spotify/Dockerfile.template
Use production images at `balenablocks` dockerhub org.
=> meta: Use balenablocks images instead of balenaplayground

docker-compose.yml
Minor update to re-open the snapcast server control port.  Doing so allows interoperability with other systems which use similar technology stacks.  For example, one can control balenaSound client volume levels via the Snap.Net Windows snapcast client or the Android Snapcast app.
=> Open port 1705 for snapcast clients to control snapcast server.

docs/01-getting-started.md
Connects-to: #307
Signed-off-by: Mark Chester <mark@chesterfamily.org>
Placed a section at the bottom of the Getting Started page that links clearly to all support options.
=> Documentation: added clear links to help on the Getting Started page

.gitignore, core/multiroom/server/Dockerfile.template, core/multiroom/server/snapserver.conf, docker-compose.yml
This adds the simple web application snapweb to the snapcast server.
The application allows to set properties of snapcast (multiroom) client
such as volume
Signed-off-by: emmanuel.jannetti@gmail.com
Connects-to: #319
=> multi-room: add snapweb to snapcast server

ARCHITECTURE.md, core/audio/balena-sound.pa, core/audio/start.sh, core/multiroom/client/Dockerfile.template, core/multiroom/client/start.sh, core/multiroom/server/Dockerfile.template, core/multiroom/server/snapserver.conf, docker-compose.yml, docs/03-customization.md
- Update snapcast to v0.22.0-r0
- Replace FIFO stream source with ALSA which significantly reduces CPU and I/O usage (fixes #294)
- Add SOUND_INPUT_LATENCY and SOUND_OUTPUT_LATENCY env vars (also helps with #294)
- Reduce multiroom-server image with multi stage builds for a slimmer image
- Reduce verbose level for both multiroom services
Connects-to: #294
=> multiroom: update snapcast to v0.22 and various improvements

plugins/spotify/start.sh
rasptify updated their librepsot debs to pull in the new changes in librespot to move away from --linear-volume and to either --mixer-linear-volume or --volume-ctrl linear. The latter seems to be the preferred option judging by their latest docs update.
Connects-to: #386
Closes: #386
Signed-off-by: Aaron Shaw <aaron@balena.io>
Co-authored-by: eiddor <roddie@krweb.net>
Co-authored-by: wusala01 <nick.london94@gmail.com>
=> spotify: fix linear volume control issue

docs/03-customization.md, plugins/spotify/start.sh
This feature allows the user to enable Spotify's audio cache by setting the SOUND_SPOTIFY_ENABLE_CACHE environment variable. The cache is now disabled by default to avoid full filesystem issues.
Connects-to: #367
Signed-off-by: Roddie Hasan <roddie@krweb.net>
=> spotify: Add option to disable Spotify's audio cache

core/audio/start.sh, core/multiroom/client/Dockerfile.template, core/multiroom/client/start.sh, core/multiroom/server/Dockerfile.template, core/multiroom/server/start.sh
Latest snapcast release on alpine edge is not working properly.
Going back to debian to get snapcast v0.23.
This increases container size considerably though :/
Connects-to: #423
=> multiroom: fix snapcast version

core/multiroom/client/Dockerfile.template, core/multiroom/client/start.sh, core/multiroom/server/Dockerfile.template, core/multiroom/server/snapserver.conf, core/multiroom/server/start.sh, core/sound-supervisor/src/SoundConfig.ts, core/sound-supervisor/src/constants.ts, core/sound-supervisor/src/index.ts, docs/03-customization.md
Changelog:
- Use multiroom block. This reduces 10x the image size for both multiroom containers (~350MB down to ~35MB, expanded). Also gives us finer control over the snapcast version being used.
- Improve fleet sync with a periodic update being sent between devices. Previously only at boot and play.
- Allow disabling fleet sync updates.
=> Multiroom improvements

plugins/airplay/start.sh
The way AirPlay service was getting the `sound-supervisor` internal IP address was incorrect. We were using `ip route | awk '/default / { print $3 }'` which in `network_mode: host` containers such as AirPlay returns the network router's IP address instead of the device IP address which is what we need to access `sound-supervisor`. 
The IP address is **only** used to halt AirPlay's initialisation until `sound-supervisor` indicates it's safe to start it (see [here](https://github.com/balenalabs/balena-sound/blob/dedeebbd53f5bcd8fc962415f5aed62bd4c23781/plugins/airplay/start.sh#L21)). This is done via a `curl` command, since we were hitting the router with the command depending on your router it would return different results which means problems due to this bug were not so easy to identify …
=> airplay: fix connection bug with airplay

.github/workflows/balena-ci.yml
balena-ci GitHub action replaces old build check and automatically builds and pushes release for balenaSound open fleet
=> meta: replace balena/build CI with balena-ci GitHub action

repo.yml
Replaced by deploy-to-balena github action
=> ci: remove balena build check

core/audio/start.sh, docker-compose.yml
I'm running [Pi-hole](https://github.com/klutchell/balena-pihole) and [balenaSound](https://github.com/balenalabs/balena-sound) mashup on RPi4 (https://www.balena.io/blog/two-projects-one-device-turn-your-raspberry-pi-into-a-multitool/).
The Pi-hole from [v2021.9.0](https://github.com/klutchell/balena-pihole/releases/tag/v2021.9.0) version is setting the custom hostname with [balenablocks/hostname](https://github.com/balenablocks/hostname) in its [docker-compose.yml](https://github.com/klutchell/balena-pihole/blob/v2021.9.0/docker-compose.yml#L36).
The latest balenaSound is still using the old way and curl the Supervisor API in its [core/audio](https://github.com/balenalabs/balena-sound/blob/master/core/audio/start.sh#L99) component.
Combining both approaches doesn't work well - the …
=> patch: Set hostname with balenablocks/hostname

core/audio/balena-sound.pa, core/audio/start.sh
Fix a bug introduced by upgrading audio block to latest version running PulseAudio v15.
PulseAudio v14 introduced significant changes to stream behavior when changing default sink (described here: https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/14.0/#significantroutingchangestodefaultsinkssources). 
Closes: #542, #543, #544, #545
=> audio: fix no sound bug

plugins/spotify/Dockerfile.template
Spotify playback is broken in librespot 0.3.1 and depending on tmigone/librespot:0.3.1-pulseaudio means we can't easily upgrade to the latest version.
Building within the project allows us to choose which version is tracked by balena-sound, [as suggested here](https://github.com/balena-labs-projects/balena-sound/issues/589#issuecomment-1310072186).
I pushed this to a balena device and it builds correctly and plays Spotify.
Fixes #589
=> Build librespot 0.4.2 in container (fixes #589)

plugins/spotify/Dockerfile.template
I have no idea why the `librespot` building isn't working (implemented in PR #610) causing issues #611 and #612.
I think we should switch to the pre-built images of v0.4.2.
[There's a list of architectures here](https://hub.docker.com/r/andrewn/librespot/tags).
[I used this script](https://github.com/andrewn/librespot-docker/blob/andrewn/librespot-v0.4.2/scripts/build-pulseaudio.sh) and have been running on a Pi model 3 A+ for a few months.
Open a PR to revert commit 9f8c623c7c6778e19ce20a99e4b0029bb85e316b. 
@maggie0002 it's up to you. Sorry about messing things up :-( 
(fixes #611, #612)
=> Use a pre-built librespot image

plugins/airplay/Dockerfile.template, plugins/airplay/start.sh, plugins/airplay/supervisor.conf
Following https://github.com/balena-labs-projects/balena-sound/issues/607  
This is an attempt to bring airplay 2 support to balena sound. 
- a Raspberry pi 4 + hifiberry DAC, that is my current multiroom master 
- a raspberry pi zero w + hifiberry miniamp, that is a multiroom client
I tested all this with `SOUND_MODE=standalone` and `SOUND_MODE=MULTI_ROOM` or `SOUND_MODE=MULTI_ROOM_CLIENT`
I noticed even before this upgrade that my raspberry pi zero had high CPU usage, and the sound was stuttering while streaming as a multiroom client. 
I was not able to properly test the sound output for this device, the stuttering persisted after the shairport's version upgrade. I am pretty sure this is a different issue, but I would be glad if other users tested on their properly working Rpi zero to …
=> Add Airplay 2 support - Upgrade shairport version

plugins/spotify/start.sh
Fix for Spotify customization variables **SOUND_SPOTIFY_DISABLE_NORMALISATION** and **SOUND_SPOTIFY_ENABLE_CACHE**. Now the variables can be defined and have no value and work correctly.
Closes: https://github.com/balena-labs-projects/balena-sound/issues/626
=> fix for bug 626 - Spotify customization variables
